### ISSUE TITLE
Jupyter notebook is not rendering the output - Displays "No renderer found for the type"

### ISSUE THREAD

**Issue by allsuff** [eclipse-theia/theia-ide#407]
### Bug Description:
I have installed all required extensions, the Jupyter notebook UI looks fine but when running the cell then no output. It displays **"No renderer found for the type"**.  Tried to change presentation.  It appears that **"Renderers for Jupyter Notebooks in Visual Studio Code"** extension is not being recognized/picked up.  It is only showing **application/vnd.code.notebook.stdout** as a mimetype option.  Using the exact replica in VSCode and it works fine there.

![image](https://github.com/user-attachments/assets/f28a1695-cbfc-423b-ae44-e3c6b3746cdc)

### Steps to Reproduce:

1.
2.
3.

### Additional Information

- Operating System: Windows 11
- Theia Version:1.54.0

**Comment by JonasHelming** [comment]
@jonah-iden

**Comment by jonah-iden** [comment]
Hi, are you seeing any errors when opening the developer tools? 
That there is only one mime type is correct in that case.
I think the basic stdout renderer is coming from the * .ipynb support* extension. Not sure though why its not being registered correctly

**Comment by jonah-iden** [comment]
I can try to take a deeper look later this week

**Comment by allsuff** [comment]
Hi, I do not see any error when opening dev tools.  There are 5 warnings related to cookies "Third party cookies will be blocked. Learn more in the Issues lab."

**Comment by jonah-iden** [comment]
ok, thanks alot for checking. I was able to reproduce the problem and it seems to be theia blueprint specific. Its not happening in normal theia. 
I'll take a deeper look sometime this week

**Comment by allsuff** [comment]
Thank you!  
I noticed one thing yesterday.  When scroll (vertical scrollbar), down the output cell, I can see the results.  The vertical scroll is not turned ON by me though.  I have the below in Theia **settings.json**.
    "output.lineHeight": 200,
    "notebook.output.wordWrap": false,
    "notebook.output.scrolling": false,
    "notebook.output.textLineLimit": 2000,
    "editor.scrollbar.horizontal": "auto"

The first line of the output cell says "No renderer found for the type".
<img width="953" alt="image" src="https://github.com/user-attachments/assets/7d4beee5-5bd2-4556-9145-4f417d5a0ad2">

**Comment by allsuff** [comment]
How to avoid this and show full output?

**Comment by jonah-iden** [comment]
Sorry, I havn't had the Time to look deeper into it. Will do that today

**Comment by jonah-iden** [comment]
@allsuff I think i found the issue. You're probably missing the [builtin notebook renderer extension](https://open-vsx.org/extension/vscode/builtin-notebook-renderers)

**Comment by jonah-iden** [comment]
we should probably add these builtin extensions to Theia-IDE by default to avoid this confusion

**Comment by allsuff** [comment]
Hi @jonah-iden, Thank you!  after adding the built-in extension, the problem does not persist anymore.  The problem is resolved.  
Thank you for all of your time & attention!!
