### ISSUE TITLE
TypeScript language server not working

### ISSUE THREAD

**Issue by davidjmemmett** [eclipse-theia/theia-ide#432]
### Bug Description:
Ctrl+Click to jump to definitions doesn't work, auto-complete doesn't work, several processes using ~500% CPU (assuming 5x100%), message in status bar "Initialising JS/TS language features" never goes away, occasionally get a message saying that the TypeScript language server crashed 5 times in the last few minutes. Attempting to do Ctrl+Space for auto-complete either results in "Loading..." in a context menu, or a list of unrelated definitions.

Funnily enough I switched over from Eclipse to Theia as I was experiencing the exact same issue with Eclipse.

### Steps to Reproduce:

1. Open a project in Theia (I have an AWS CDK project) v1.55.0 (latest available via Snap)
2. Try to use any of the TypeScript language features
3. Observe high CPU usage and none of the Typescript language features working

![image](https://github.com/user-attachments/assets/48fbde7e-b961-4005-aefa-45a5f94b7645)

The only message in the log file `~/.config/Theia\ IDE/logs/main.log` is:
`SNAP env is defined, updater is disabled` repeated several times.

### Additional Information

- Operating System: Ubuntu 22.04.5 LTS 
- Theia Version: 1.55.0 via Snap

**Comment by davidjmemmett** [comment]
Perhaps we can close this issue. Turns out having [an enormous CDK output directory](https://github.com/aws/aws-cdk/issues/2869#issuecomment-2550997456) might kill a language server.

**Comment by gshpychka** [comment]
> Perhaps we can close this issue. Turns out having [an enormous CDK output directory](https://github.com/aws/aws-cdk/issues/2869#issuecomment-2550997456) might kill a language server.

Only if you don't exclude `cdk.out` in your `tsconfig.json`
